version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./www/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php-server
    # command: docker-php-ext-install pdo_mysql
    networks:
      - internal
    volumes:
      - ./www/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  mysql:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data_db:/var/lib/mysql
      - ./mysql-data/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: images
    networks:
      - internal
  image-server:
    image: image-server
    ports:
      - "3000:3000"
    volumes:
      - ./image-server/:/app/
    networks:
      - internal
  bind9:
    container_name: dns-demo
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Berlin
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns-config/:/etc/bind/
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped
    networks:
        - internal

volumes:
  data_db:
networks:
  internal:
    driver: bridge
