version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./www/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php-server
    # command: docker-php-ext-install pdo_mysql
    networks:
      - internal
    volumes:
      - ./www/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: images

volumes:
  db_data:
networks:
  internal:
    driver: bridge
